name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: pizza
          POSTGRES_USER: pizzauser
          POSTGRES_PASSWORD: pizzapass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U pizzauser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_URL: jdbc:postgresql://postgres:5432/pizza
      DB_USERNAME: pizzauser
      DB_PASSWORD: pizzapass
      JWT_SECRET: mysupersecuresecretthatatleast32characterslong
      VITE_API_URL: http://arainea-backend.arainea.svc.cluster.local:8080

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --build-arg VITE_API_URL=${{ env.VITE_API_URL }} \
            -t cxgdn/arainea-frontend:latest

      - name: Login to Docker Hub
        run: docker login -u cxgdn -p dckr_pat_NQDxIKYdnllF5XD5HRDypIEYy1U

      - name: Push image
        run: docker push cxgdn/arainea-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout Deployment repo
        uses: actions/checkout@v4
        with:
          repository: AraiNea/Deployment
          path: deployment

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Apply manifests
        run: |
          kubectl apply -f deployment/k8s/namespace.yaml
          sleep 3
          kubectl apply -f deployment/k8s/
          
  cypress:
    needs: deploy
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
  
      - name: Load kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | sed 's/\\n/\n/g' > ~/.kube/config
          chmod 600 ~/.kube/config
  
      - name: Debug kubeconfig
        run: |
          kubectl config view
          kubectl get nodes
  
      - name: Debug Services
        run: |
          echo "===== Services in arainea ====="
          kubectl get svc -n arainea -o wide
